[[constraint]]
  name = "github.com/valyala/fasthttp"
  branch = "master"

[[constraint]]
  name = "github.com/buaazp/fasthttprouter"
  branch = "master"

[[constraint]]
  name = "github.com/savsgio/go-logger"
  version = "2.1.0"

[[override]]
  name = "github.com/klauspost/compress"
  branch = "master"

[[override]]
  name = "github.com/klauspost/cpuid"
  branch = "master"

[[override]]
  name = "github.com/klauspost/crc32"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
